relative-paths: true
models:
    - model.intgemm.bin
vocabs:
    - vocab.enfa.spm
    - vocab.enfa.spm
shortlist:
    - lex.s2t.bin
    - 50
    - 50
beam-size: 1
normalize: 1.0
word-penalty: 0
mini-batch: 16
maxi-batch: 1000
maxi-batch-sort: src
workspace: 512
max-length-factor: 2.0
skip-cost: true
int8shift: true
