relative-paths: true
models:
  - model.npz
vocabs:
  - vocab.deen.spm
  - vocab.deen.spm
beam-size: 1
normalize: 1.0
word-penalty: 0
mini-batch: 64
maxi-batch: 1000
maxi-batch-sort: src
workspace: 2000
max-length-factor: 2.5
skip-cost: true
